# Prometheus custom values for Concord JMX metrics
# This file adds a scrape job for Ratis JMX metrics from the Concord distributed hash map

serverFiles:
  prometheus.yml:
    scrape_configs:
      # Concord JMX Metrics - Ratis distributed consensus metrics
      - job_name: 'concord-jmx-metrics'
        scrape_interval: 15s
        static_configs:
          - targets:
            - 'concord-0.concord-headless.concord.svc.cluster.local:9090'
            - 'concord-1.concord-headless.concord.svc.cluster.local:9090'
            - 'concord-2.concord-headless.concord.svc.cluster.local:9090'
            labels:
              app: 'concord'
              metrics_type: 'jmx'

