kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - protocol: TCP
    containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - protocol: TCP
    containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
  - protocol: TCP
    containerPort: 30100
    hostPort: 30100 # for elasticmq connection from outside of the container
    listenAddress: "0.0.0.0"
  - protocol: TCP
    containerPort: 30101
    hostPort: 30101 # for redis connection from outside of the container
    listenAddress: "0.0.0.0"
  - protocol: TCP
    containerPort: 30102
    hostPort: 30102 # for postgres connection from outside of the container
    listenAddress: "0.0.0.0"